services:
  - type: web
    name: sentiment-explorer-flask-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 index:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production